### ISSUE TITLE
AttributeError: module 'typing_extensions' has no attribute 'Union'

### ISSUE THREAD

**Issue by huynd26** [typesense/typesense-python#80]
Hi, I got an error when upgrading Typesense from version 0.21.0 to 1.0.3
`
_SequenceTypes = typing.Union[\nAttributeError: module 'typing_extensions' has no attribute 'Union'\n", "path": "/webapps/bookclubz/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "syspath": ["/tmp/ansible_community.general.django_manage_payload_2wkzk7x5/ansible_community.general.django_manage_payload.zip", "/usr/lib/python310.zip", "/usr/lib/python3.10", "/usr/lib/python3.10/lib-dynload", "/usr/local/lib/python3.10/dist-packages", "/usr/lib/python3/dist-packages"]}
`
Python version: 3.10
Typing_extension: 4.13.1

Hopefully there is a solution or a correction version to solve it.  Many Thanks!

**Comment by tharropoulos** [comment]
Hey there, are you using a virtual environment for dependency management? This error is a first for me and we actually run our tests against multiple Python versions.

I'll investigate what's going on here

**Comment by huynd26** [comment]
Yes, I'm using a virtual environment for dependency management. Thank you for the timely feedback!

**Comment by tharropoulos** [comment]
I just upgraded from 0.21.0 to 1.0.3 normally without any errors. Did this occur when installing or on some other pipeline?d

**Comment by huynd26** [comment]
> I just upgraded from 0.21.0 to 1.0.3 normally without any errors. Did this occur when installing or on some other pipeline?d

What is the typing_extensions version you installed? Thank you.

**Comment by tharropoulos** [comment]
`typing_extensions==4.13.2`
